### ISSUE TITLE
Help with the syntax of relationship searches

### ISSUE THREAD

**Issue by NickTerrafranca** [encoreshao/crunchbase-ruby-library#10]
I am having difficulty with the syntax of relationship searches.
If I have a company name like BASF (and I have the uuid for that organization record) and I want a list of people who are associated with the BASF record, how would I compose that query?

**Comment by encoreshao** [comment]
Hi Nick,

Do you want to get all the BASF team? Like this page's data - https://www.crunchbase.com/organization/basf/current_employees/current_employees_image_list

maybe you are looking for this: `Crunchbase::Model::CurrentTeam.organization_lists('basf', page: 1, items_per_page: 250)`

**Comment by NickTerrafranca** [comment]
Hi encoreshao, first of all thank you for the reply!
I think PersonSummary would be better than CurrentTeam ```Crunchbase::Model::PersonSummary.organization_lists('basf', page: 1, items_per_page: 250) ``` but this returns a ```NameError: uninitialized constant Crunchbase::Model::PersonSummary::RESOURCE_LIST ```
PersonSummary does list  #organization_lists as being included from Request::Client

**Comment by NickTerrafranca** [comment]
Here is another issue: 
```
people = Crunchbase::Model::CurrentTeam.organization_lists("basf", page: 1, items_per_page: 500)
=> #<Crunchbase::Model::Search:0x007fa1e9b1a3e0 ...
# works great!
people.results.first.person
=> <Crunchbase::Model::Person...>
# also works great!
permalink = people.results.first.person.permalink
=> 'markus-solibieda'
# so far so good!
client = Crunchbase::Client.new
# using the example in the documentation
person = client.get('Person', permalink) 
=> nil
```
The example above to "Get Person by the permalink" returns nil for a permalink that is know to be valid. Am I missing something?

**Comment by NickTerrafranca** [comment]
These items copied from the documentation also return nil:
```
response = client.get('Organization', 'facebook')
response = client.get('Organization', 'facebook', 'PastTeam')
```

**Comment by encoreshao** [comment]
Oh ... I'm sorry for this! I updated the method, but did not update README.md.

Please try `response = client.get('facebook', 'Organization', 'PastTeam')`
