### ISSUE TITLE
Search by multiple locations on Organization?

### ISSUE THREAD

**Issue by skazzaks** [encoreshao/crunchbase-ruby-library#14]
Is there a way to search for multiple locations? The crunchbase documentation for "locations" under "Organization" says "Filter by location names (comma separated, AND'd together) e.g. locations=California,San Francisco" When I try something similar, I always get no results:
` pry(main)> @client.search({locations: 'Berlin,Germany', sort_order: 'created_at ASC'}, 'organizations')
=> #<Crunchbase::Model::Search:0x00007f9fd8be0ff8
 @current_page=1,
 @next_page_url=nil,
 @pages=1,
 @per_page=100,
 @prev_page_url=nil,
 @query={:locations=>"Germany,Berlin", :sort_order=>"created_at ASC", :page=>1, :order=>"created_at ASC"},
 @results=[],
 @sort_order="created_at ASC",
 @total_items=0>
`

Is there a way to achieve this? Thanks!

**Comment by encoreshao** [comment]
@skazzaks, I checked the search function and it really didn't work. I found a bug here that there were no correct encoding params.

It has been fixed and has been pushed to rubygems (0.3.4).

Thanks for your attention!

Encore

**Comment by skazzaks** [comment]
Thanks so much for this, Encore!
