### ISSUE TITLE
Queries timing out

### ISSUE THREAD

**Issue by skazzaks** [encoreshao/crunchbase-ruby-library#15]
I've been using this gem for a while now and everything has worked fine (thank you greatly for it!). However, as of yesterday, calls have begun to timeout, resulting in:
```
Timeout::Error: execution expired
from /Users/devon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/protocol.rb:181:in `wait_readable'
```
Here is an example call that fails about half the time:
`@client.search({updated_since: last_search_date, page: page, locations: locations, sort_order: 'created_at DESC'}, 'organizations')
`
I haven't changed anything, so I don't know why things have gotten slower, but is there a way to change the timeout so it is more forgiving?

Thanks!

**Comment by encoreshao** [comment]
@skazzaks - I added a new option (timeout) and you can change the timeout limit in application's.

> Crunchbase::API.timeout = 60 # Default value is 60

By the way: Please upgrade to the latest version (0.3.6).

**Comment by encoreshao** [comment]
thanks @skazzaks  for your comments to help us improve this library!
